# Generated by Django 3.1.2 on 2020-10-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fileManager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=fileManager.models.user_directory_path, validators=[fileManager.models.file_size])),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
